name: rag cicd

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy Helm chart
        run: |
          helm upgrade --install rag-first ./helm/rag-first --namespace rag-kk



 
     
